version: '3'
services:
  parity:
    image: ethcore/parity:v1.6.5
    ports:
      - 8545:8545
    volumes:
      - ~/.parity:/root/.parity
    entrypoint: /parity/parity --warp --jsonrpc-interface '0.0.0.0' --jsonrpc-hosts all -d /root/.parity --no-ui --no-ipc --no-dapps
  mongo:
    image: mongo:3.4.2
    volumes:
      - ~/.mongo:/data/db
    ports:
      - 27017:27017
    command: mongod --storageEngine wiredTiger
  optimus:
    image: antoniojuliano/optimus
    ports:
      - 3002:3002
    volumes:
      - ~/.optimus:/home/ethnexus/app/bin/soljson/
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  redis:
    image: redis:3.2.8-alpine
    ports:
      - 6379:6379

volumes:
  esdata1:
    driver: local
